name: Demo vulnerable workflow

on:
  issues:
    types: [opened]

env:
  # Environment variable for demonstration purposes
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DESCRIPTION: ${{github.event.issue.body}}

jobs:
  vuln_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - env:
          TITLE: ${{github.event.issue.title}}
          DESCRIPTION: ${{github.event.issue.body}}
          
        run: |
          echo "ISSUE TITLE: $TITLE"
          echo "ISSUE DESCRIPTION: $DESCRIPTION"

  vuln_job_2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - env:
          TITLE: ${{github.event.issue.title}}
          
        run: |
          echo "ISSUE TITLE: ${{ env.TITLE }}"
          echo "ISSUE DESCRIPTION: ${{ env.DESCRIPTION }}"


